from .alias import *
from .bookmark import *

__version__ = "2.2.3"

__all__ = [
    "ALIAS_1_44MB_FLOPPY_DISK",
    "ALIAS_400KB_FLOPPY_DISK",
    "ALIAS_800KB_FLOPPY_DISK",
    "ALIAS_EJECTABLE_DISK",
    "ALIAS_FIXED_DISK",
    "ALIAS_HFS_VOLUME_SIGNATURE",
    "ALIAS_KIND_FILE",
    "ALIAS_KIND_FOLDER",
    "ALIAS_NETWORK_DISK",
    "ALIAS_NO_CNID",
    "URL",
    "Alias",
    "AppleShareInfo",
    "Bookmark",
    "Data",
    "TargetInfo",
    "VolumeInfo",
    "__version__",
    "kBookmarkCNIDPath",
    "kBookmarkContainingFolder",
    "kBookmarkCreationOptions",
    "kBookmarkFileCreationDate",
    "kBookmarkFileID",
    "kBookmarkFileName",
    "kBookmarkFileProperties",
    "kBookmarkPath",
    "kBookmarkSecurityExtension",
    "kBookmarkTOCPath",
    "kBookmarkUID",
    "kBookmarkURLLengths",
    "kBookmarkUserName",
    "kBookmarkVolumeCreationDate",
    "kBookmarkVolumeName",
    "kBookmarkVolumePath",
    "kBookmarkVolumeProperties",
    "kBookmarkVolumeSize",
    "kBookmarkVolumeURL",
    "kBookmarkVolumeUUID",
    "kBookmarkWasFileReference",
]
